image: openjdk:11-jdk

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/
    - build

stages:
  - build

before_script:
  - "export GRADLE_USER_HOME='pwd'/.gradle"

build:
  stage: build
  script:
    - "chmod 774 ./gradlew"
    - "./gradlew clean build test jar deploymentJar allJavadoc -Dfile.encoding=UTF-8 -i --stacktrace"
  artifacts:
    paths:
      - "build/javadoc/*"
      - "*/build/libs/*"
      - "cloudnet-modules/*/build/libs/*"
      - "cloudnet-plugins/*/build/libs/*"
  only:
    - master
